Adding callback functionality to plugin
mentaljam/rollup-plugin-favicons pull request #3
Opened 2020-08-27 22:00 UTC by Steakeye

Passing callback through to `favicons` package and providing functionality to call the callback when using cached assets.
Other additions are primarily in order to get the build to pass as it was failing for me.

2020-08-27 22:01 UTC, Steakeye commented
Obviously, if you don't want this feature then that's fine, it works for my needs and I can just keep my fork :wink:

2020-09-17 09:32 UTC, mentaljam requested changes
Can you, please, squash 6d636bbdf7daff9f344d8f9a3c9427ac9452efbd with 5a36c8ee2067f93b5da225cc23a172573c325e65?

2020-09-17 09:34 UTC, mentaljam requested changes
Also, please, drop 788c5910c70a5531b4bb02e0d7489ef318ee9912 and f5a6707dfde43363735377f891c62849547cde3e.

2020-09-17 09:38 UTC, mentaljam commented
Thank you for your contribution and sorry for not answering for so long. I like the idea to allow developer to choose between emitting assets with Rollup and passing own callback. I will pull your commits after applying my changes requests.

2021-06-28 14:38 UTC, Steakeye commented
> Also, please, drop [788c591](https://github.com/mentaljam/rollup-plugin-favicons/commit/788c5910c70a5531b4bb02e0d7489ef318ee9912) and [f5a6707](https://github.com/mentaljam/rollup-plugin-favicons/commit/f5a6707dfde43363735377f891c62849547cde3e).

Sorry this took so long, I started a new job and forgot about this! Dropped those commits.

2021-06-30 10:03 UTC, merged

2021-06-30 10:19 UTC, mentaljam commented
Thank you!